[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.2.1" }
selene = { github = "Kampfkarren/selene", version = "0.25.0" }
stylua = { github = "JohnnyMorganz/StyLua", version = "0.17.1" }
wally = { source = "UpliftGames/wally", version = "0.3.1" }